from typing import Protocol


class ProtocolManager(Protocol):
    slug: str

    async def detect(self, ssh, server): ...

    async def import_existing(self, ssh, server): ...

    async def install(self, ssh, server, options): ...

    async def uninstall(self, ssh, server) -> None: ...

    async def add_client(self, ssh, server, payload): ...

    async def remove_client(self, ssh, server, client) -> None: ...

    async def sync_stats(self, ssh, server): ...

    async def get_status(self, ssh, server): ...
